### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by LappleApple** [zalando-stups/dependency-spec#3]
Are you guys still working on it/planning to work on it?

**Comment by hjacobs** [comment]
Our reference implementation is https://github.com/zalando-stups/magnificent

Not sure if everything is "in-sync". @prayerslayer probably knows.

**Comment by LappleApple** [comment]
thanks, @hjacobs. @prayerslayer, can you drop a line on this repo? Doesn't seem to be too much happening here..

**Comment by prayerslayer** [comment]
Ohai, was on vacation when this was opened. The API of Magnificent is completely out of sync with this as we implemented a simpler version. If it was for me we can delete/move this repository.

**Comment by LappleApple** [comment]
Thanks, @prayerslayer. I'll delete.
